version: '3'

services:

    redis:
      image: redis:latest
      ports:
        - 6380:6380
        - 6379:6379

    redisCommander:
      image: tenstartups/redis-commander
      command: '--redis-host redis'
      links:
        - redis:redis
      ports:
        - 8081:8081

    mongo:
      image: mongo:latest
      ports:
        - 27017:27017
      command: -smallfiles -nojournal