version: '3'

services:

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: spring
      MYSQL_DATABASE: section4
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  db2:
    image: mysql:5.7
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: spring
      MYSQL_DATABASE: section4_2
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
