version: '3'
services:

  section-3-5-service:
    build: ../.
    ports:
      - 8080
    hostname: app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:8080/hello"]
      interval: 10m
      timeout: 10s
      retries: 5

  nginx:
    build: ../nginx
    restart: always
    ports:
      - 80:80
    hostname: proxy
    depends_on:
      - section-3-5-service
    links:
      - section-3-5-service:app
    entrypoint: dockerize -wait http://app:8080/hello nginx -g 'daemon off;'